# Generated by Django 4.1 on 2022-08-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='')),
                ('project_des', models.TextField(blank=True, null=True)),
                ('project_link', models.CharField(max_length=300)),
                ('project_code_link', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('OLD', 'OLD')], max_length=4)),
            ],
        ),
    ]
