# Generated by Django 4.1 on 2022-08-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_name',
            field=models.CharField(default='Music Project', max_length=100),
            preserve_default=False,
        ),
    ]
