# Generated by Django 4.1 on 2022-09-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_projects_total_down_vote_projects_total_up_vote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='App.tag'),
        ),
    ]
